
GET http://localhost:8000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTAsInJvbGUiOiJTdHVkZW50IiwiZW1haWwiOiJzb3RoZWFyYUBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDM5MDI0NywiZXhwIjoxNzg0NDc2NjQ3fQ.MdbvOPdTg_HCeREspcvYHIg9_UGqF_TRaqyQcany1Jk

###
get  http://localhost:8000/api/courses/


###
PATCH   http://localhost:8000/api/lecturers/courses/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTUsInJvbGUiOiJsZWN0dXJlciIsImVtYWlsIjoic29yaUBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDQyOTMyNCwiZXhwIjoxNzg0NTE1NzI0fQ.XyDXonmaYMUbI9ZZEBKimmm8JRMj8pfaD-NLq8l3kG4

{
    "user_id": 110,
    "course_id": 108,
    "status": "waiting"}
###
POST http://localhost:8000/api/auth/signup
Content-Type: application/json

{
    "full_name": "naruto",
    "email": "naruto@example.com",
    "password": "12345",
    "gender": "Male",
    "dob": "2026/08/07",
    "phone_number": "09876543"
}
###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{ 
    "email": "sotheara@example.com",
    "password": "123456"
}
###
GET http://localhost:8000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTAsInJvbGUiOiJTdHVkZW50IiwiZW1haWwiOiJzb3RoZWFyYUBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDQzNTcyNCwiZXhwIjoxNzg0NTIyMTI0fQ.j7xY6Syq8fgbP2CWrSGgUi2Q6sNWMsuJKO9Xk9M2In4
###
GET http://localhost:8000/api/students/110/dashboard?
Content-Type: application/json
###
patch   http://localhost:8000/api/admin/dashboard/update
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTcsInJvbGUiOiJBZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJpYXQiOjE3ODQzNDc4MzUsImV4cCI6MTc4NDQzNDIzNX0.GIP5pe8tZFZ3o9wPyhHyJVBvLeFmPQ2dgeEVfWpZvHY

{
    "course_id": 103,
    "status": "waiting"
}

### 
GET http://localhost:8000/api/admin/dashboard/activity
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTUsInJvbGUiOiJsZWN0dXJlciIsImVtYWlsIjoic29yaUBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDQ3NDIzOSwiZXhwIjoxNzg0NTYwNjM5fQ.UdxINfg7-CyE5Q42TZylDrfhnLxMJ_pUByppMQP-rD8

###
PATCH  http://localhost:8000/api/courses/106/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMTUsInJvbGUiOiJsZWN0dXJlciIsImVtYWlsIjoic29yaUBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDQ3MDgwMywiZXhwIjoxNzg0NTU3MjAzfQ.xVlN0m7ndKt7AQY1f2bzBw9oQXZFZCQkAnunDFMug3w

{
    "title": "Introduction to Machine Learning",
    "duration":  14033,
    "sub_description": "This course is about machine learning",
    "description": "Learn Machine Learning in a way that is accessible to absolute beginners. You will learn the basics of Machine Learning and how to use TensorFlow to implement many different concepts.",
    "price": 0,
    "category_id": "10",
    "video_id": "i_LwzRVP7bg"
}
###




